### ISSUE TITLE
Installing issues Odin due to error 'SELF_SIGNED_CERT_IN_CHAIN

### ISSUE THREAD

**Issue by drirem0** [infor-cloud/m3-h5-sdk#122]
Hello,

We have come across an issue installing Odin. 
When we run NPM INSTALL we're getting the following errors.     (SELF_SIGNED_CERT_IN_CHAIN  (see below)

Firstly obviously trying to understand the error. 
And then what NPM commands are available to get past this issue for 'npm install' to finish correctly.

3927 info run puppeteer@3.0.4 install node_modules/@infor-up/m3-odin-cli/node_modules/puppeteer node install.js3928 info run puppeteer@3.0.4 install { code: 1, signal: null }3929 timing reify:rollback:createSparse Completed in 10828ms3930 timing reify:rollback:retireShallow Completed in 0ms3931 timing command:install Completed in 87186ms3932 verbose stack Error: command failed3932 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\@npmcli\promise-spawn\index.js:64:27)3932 verbose stack     at ChildProcess.emit (node:events:526:28)3932 verbose stack     at maybeClose (node:internal/child_process:1092:16)3932 verbose stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5)3933 verbose pkgid puppeteer@3.0.43934 verbose cwd C:\Users\mooresla3935 verbose Windows_NT 10.0.190443936 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "@infor-up/m3-odin-cli"3937 verbose node v16.14.13938 verbose npm  v8.5.03939 error code 13940 error path C:\Users\mooresla\AppData\Roaming\npm\node_modules\@infor-up\m3-odin-cli\node_modules\puppeteer3941 error command failed3942 error command C:\WINDOWS\system32\cmd.exe /d /s /c node install.js3943 error ERROR: **Failed to set up Chromium r737027! Set "PUPPETEER_SKIP_DOWNLOAD"** env variable to skip download.3943 error Error: self signed certificate in certificate chain3943 error     at TLSSocket.onConnectSecure (node:_tls_wrap:1530:34)3943 error     at TLSSocket.emit (node:events:526:28)3943 error     at TLSSocket._finishInit (node:_tls_wrap:944:8)3943 error     at TLSWrap.ssl.onhandshakedone (node:_tls_wrap:725:12)

3943 error   -- ASYNC --3943 error     at BrowserFetcher.<anonymous> (C:\Users\mooresla\AppData\Roaming\npm\node_modules\@infor-up\m3-odin-cli\node_modules\puppeteer\lib\helper.js:82:19)3943 error     at fetchBinary (C:\Users\mooresla\AppData\Roaming\npm\node_modules\@infor-up\m3-odin-cli\node_modules\puppeteer\install.js:114:27)3943 error     at download (C:\Users\mooresla\AppData\Roaming\npm\node_modules\@infor-up\m3-odin-cli\node_modules\puppeteer\install.js:42:9) {3943 **error   code: 'SELF_SIGNED_CERT_IN_CHAIN'3943** error }3944 verbose exit 13945 timing npm Completed in 88219ms3946 verbose unfinished npm timer reify 16478378163563947 verbose unfinished npm timer reify:build 16478378914763948 verbose unfinished npm timer build 16478378914803949 verbose unfinished npm timer build:deps 16478378914813950 verbose unfinished npm timer build:run:install 16478378917593951 verbose unfinished npm timer build:run:install:node_modules/@infor-up/m3-odin-cli/node_modules/puppeteer 1647837891761

**Comment by swuendri** [comment]
Hello @drirem0,

it seems you are behind a corporate proxy, right? Maybe https://stackoverflow.com/questions/34498736/npm-self-signed-cert-in-chain will help you? But after solving this issue you will run into the same issue mentioned in #89. I couldn't solve this issue until now ☹️.
