### ISSUE TITLE
Problem using login command 4 for multitenant

### ISSUE THREAD

**Issue by jtharing** [infor-cloud/m3-h5-sdk#165]
Hi!

I am having problem establishing connection to our M3 Cloud multi-tenant to develop H5SDK apps. I am following the instructions on github (https://github.com/infor-cloud/m3-h5-sdk/issues/55) but i am receiving an error when trying to retrieve the session cookie. The only parameter not explicitly stated is the url-to-m3 one, where i assumed. https://m3prdeuc1.m3.eu1.inforcloudsuite.com. Is this a correction assumption?  I have followed the previous "installation"steps stated https://github.com/infor-cloud/m3-h5-sdk.

Any idea what i might be doing wrong?

Thanks!

This is the command i am running when i receive the error:

odin login -c --m3 https://m3prdeuc1.m3.eu1.inforcloudsuite.com Odin.ionapi

(the Odin.ionapi file is located in the same directory as the project itself)

-------------Command Promt messages----------------
C:\Users\thajoh0.DOMAIN\MeridionCETest>odin login -c --m3 https://m3prdeuc1.m3.eu1.inforcloudsuite.com Odin.ionapi
A browser will pop up where you will be asked to sign in and approve the authorization request.
Waiting for ION API Token
Got ION API token
Visiting 'https://m3prdeuc1.m3.eu1.inforcloudsuite.com/mne' to get session cookie
**TypeError: _page._client.send is not a function**
at getAllCookies (file:///C:/Users/thajoh0.DOMAIN/AppData/Roaming/npm/node_modules/@infor-up/m3-odin-cli/dist/commands/login.js:149:59)
at Timeout.<anonymous> (file:///C:/Users/thajoh0.DOMAIN/AppData/Roaming/npm/node_modules/@infor-up/m3-odin-cli/dist/commands/login.js:135:39)
at listOnTimeout (node:internal/timers:568:17)
at process.processTimers (node:internal/timers:511:7)
ERROR: Login command failed
Usage: odin [options] [command]

**Comment by swuendri** [comment]
Hi @jtharing, you should use the ION API to access M3 and not M3 APIs directly. If I'm right this possibility was cancelled by Infor. Please use `odin login -c Odin.ionapi` to retrieve an access token. And you application should only call ION APIs.

**Comment by wesped0** [comment]
Hi @jtharing, there is an issue when retrieving the cookies in the getAllCookies method due to a change in the puppeteer library. 

In login.js, if you change the code from

const getAllCookiesResponse = await _page._client.send('Network.getAllCookies');

to 

const cookies = await _page.cookies();
return cookies;

it will work.

**Comment by ismail-spoon** [comment]
I'm having similar problem which I mentionned in this issue. 
#174

**Comment by dhenningsver** [comment]
> Hi [@jtharing](https://github.com/jtharing), there is an issue when retrieving the cookies in the getAllCookies method due to a change in the puppeteer library.
> 
> In login.js, if you change the code from
> 
> const getAllCookiesResponse = await _page._client.send('Network.getAllCookies');
> 
> to
> 
> const cookies = await _page.cookies(); return cookies;
> 
> it will work.

Do this still work for you? I tried it but the process stops at "Visiting 'https://m3prdeuc1b.m3.eu1.inforcloudsuite.com/mne' to get session cookie" and nothing more happens.

**Comment by jjones-4173** [comment]
I am also having this issue - I tried the fix from @wesped0 but ran into the same issue that @dhenningsver describes. It seems the puppeteer method being used to retrieve the session cookie is not getting the cookies from the correct domain. I have need of the ability to use bookmarks in multi tenant cloud environment, so I am trying to get this working.

**Comment by stewartrutledge** [comment]
I might not be understanding the issue, but doesn't multi-tenant already work with odin?

`odin login H5.ionapi --update-config`
then
`odin serve --multi-tenant --ion-api`

**Comment by whernebrink** [comment]
As @dhenningsver said, should have been solved in latest release where we created a new login command.
